"""Generate the SQL example sets, one per postcode product, from the schemas.

    python -m simd_ingest.sql_examples          # rewrites docs/sql/spd/*.sql and docs/sql/sspl/*.sql

Two sets with a common output core and product-specific raw context:

    docs/sql/spd/   reads postcode_simd_history (key pc_norm, introduced_on); also link_as_of.sql
    docs/sql/sspl/  reads postcode_simd         (key pc_norm)

Each query is standalone and reads top to bottom as numbered steps. The SPD set performs the
latest-life and A-part selection that NRS performed upstream when it built the SSPL; linked
suffix resolution also differs because SSPL keeps whole postcodes. The generated files are
committed and a test checks that they match this generator, so a new edition or a changed
header cannot leave them stale.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from .core.sources import load_registry
from .core.text_output import load_contract
from .lookup import GUIDANCE_TABLE_4

PACKAGE = Path(__file__).resolve().parent
ROOT = PACKAGE.parent

# Output name -> stored column suffix, in output order. Every stored measure of an edition.
MEASURES = [
    ("simd_rank", "rank"),
    ("phs_pw_scotland_quintile", "pw_scotland_quintile"), ("phs_pw_scotland_decile", "pw_scotland_decile"),
    ("phs_pw_hb_quintile", "pw_hb_quintile"), ("phs_pw_hb_decile", "pw_hb_decile"),
    ("phs_pw_hscp_quintile", "pw_hscp_quintile"), ("phs_pw_hscp_decile", "pw_hscp_decile"),
    ("phs_pw_ca_quintile", "pw_ca_quintile"), ("phs_pw_ca_decile", "pw_ca_decile"),
    ("phs_pw_most15pc", "most15pc"), ("phs_pw_least15pc", "least15pc"),
    ("gov_uw_scotland_quintile", "uw_scotland_quintile"), ("gov_uw_scotland_decile", "uw_scotland_decile"),
    ("gov_uw_scotland_vigintile", "uw_scotland_vigintile"),
]
GEOGRAPHY = ["hb", "hscp", "ca"]
SHARED_BEGIN = "-- BEGIN shared: from here to END shared the text is identical in link_by_era.sql and link_latest.sql of this set."
SHARED_END = "-- END shared"

PRODUCTS = {
    "spd": dict(
        contract_table="history",
        table="postcode_simd_history", parquet="results/postcode_simd_history.parquet", key="(pc_norm, introduced_on)",
        schema="output_schema_history.yaml", raw_source="directory", release_column="spd_release",
        index_source="spd", allocation="postcode_grid_reference",
        product="Scottish Postcode Directory (SPD)",
        did_upstream="nothing: every life of every postcode is a row, and split postcodes are A/B/C rows"),
    "sspl": dict(
        contract_table="main",
        table="postcode_simd", parquet="results/postcode_simd.parquet", key="pc_norm",
        schema="output_schema.yaml", raw_source="lookup", release_column="sspl_release",
        index_source="sspl", allocation="oa2022_centroid",
        product="Scottish Statistics Postcode Lookup (SSPL)",
        did_upstream="kept only the latest life of each postcode and made split postcodes whole on the A part"),
}


def _editions(registry) -> list:
    return [(e["key"], int(e["dz_vintage"])) for e in registry.phs_editions]


def _vintages(editions) -> list:
    return sorted({v for _, v in editions})


def _case(expr: str, branches: list, alias: str, quote=True) -> str:
    lines = [f"           CASE {expr}"]
    for when, then in branches:
        w = f"'{when}'" if quote else str(when)
        lines.append(f"               WHEN {w:<8} THEN {then}")
    lines.append(f"           END AS {alias}")
    return "\n".join(lines)


VARIANTS = {"era": "link_by_era.sql", "latest": "link_latest.sql", "asof": "link_as_of.sql"}
FILES = {"spd": ("era", "latest", "asof"), "sspl": ("era", "latest")}


def _header(name: str, p: dict, variant: str) -> str:
    aim = {"era": "edition chosen by the YEAR OF THE HEALTH DATA (PHS v3.5 Table 4, section 3.2.1.1)",
           "latest": "ONE edition for the whole study (PHS v3.5 section 3.2.1.2)",
           "asof": "the postcode LIFE VALID ON THE ADDRESS DATE, edition by the year of the health data"}[variant]
    return f"""-- {name.upper()} SET, {p['product']}: {aim}.
-- Reads {p['table']}, imported from {p['parquet']} with its natural key {p['key']}.
-- Standalone: no view, no other script, no other postcode product. Nothing is recalculated.
-- NRS did upstream: {p['did_upstream']}.
-- Steps are numbered; each names the guidance it follows or says it is a project choice.
-- Guidance: PHS deprivation guidance v3.5 (Table 4 p.17, sections 3.1 to 3.4, Appendix A
-- pp.28-30), the PHS postcode-file page, the NRS SSPL information note and NRS dictionaries.
-- Executed on DuckDB and on SQL Server 2022; see ../LINKAGE_BY_ERA.md for the import recipe.
-- Columns named in export_contract.yaml are not returned; the Parquet keeps them.
-- Generated by python -m simd_ingest.sql_examples from the schemas; edit the generator.
"""


def _inputs_and_edition(variant: str, editions: list) -> str:
    table4 = ",\n".join(f"        ({first}, {last}, '{ed}', {dict(editions)[ed]})" for first, last, ed in GUIDANCE_TABLE_4)
    if variant == "asof":
        return f"""WITH inputs AS (
    -- STEP 1. INPUT. Replace this SELECT with:
    --   SELECT id, postcode, address_date, CAST(NULL AS int) AS analysis_year FROM your_cohort
    -- address_date must relate to this person's address; do not assume a general record edit
    -- date is a residence date. Selecting a life on that date is a project policy. For an
    -- SMR01 episode the admission date is both the address date and the year of the event.
    -- analysis_year is an OVERRIDE, and null is the normal case: leave it null and the SIMD
    -- edition comes from the year of the address date. Set it to one constant for every row to
    -- hold a single edition across a whole trend, which PHS v3.5 section 3.2.1.2 describes.
    -- This row derives its edition: 2005 selects SIMD 2006, and the address date selects the
    -- life this postcode had then, which is not its current one.
    SELECT 1 AS id, CAST('AB11 5FA' AS varchar(32)) AS postcode,
           CAST('2005-06-10' AS date) AS address_date, CAST(NULL AS int) AS analysis_year
),
requested AS (
    -- STEP 2. KEY. Uppercase and remove ASCII spaces, keeping the original text: the same rule
    -- as ingestion (project choice). Nothing is repaired and an NRS A/B/C suffix is not
    -- removed, so supply the ordinary postcode as a person writes it. Duplicate inputs stay.
    SELECT id, postcode, address_date,
           -- The override, or the year the address date falls in. One input covers the usual
           -- case; the reported analysis_year below is whichever was used.
           COALESCE(analysis_year, YEAR(address_date)) AS analysis_year,
           NULLIF(UPPER(REPLACE(postcode, ' ', '')), '') AS postcode_key
    FROM inputs
),
era AS (
    -- STEP 3. EDITION. PHS v3.5 Table 4, printed p.17: the year of the health data chooses the
    -- SIMD edition, and the edition fixes the data-zone vintage. Before 1996 there is no SIMD;
    -- the guidance points to Carstairs, which this table does not carry.
    SELECT * FROM (VALUES
{table4}
    ) AS v(year_from, year_to, edition, data_zone_vintage)
),
chosen AS (
    SELECT r.id, r.postcode, r.address_date, r.analysis_year, r.postcode_key,
           e.edition AS simd_edition, e.data_zone_vintage,
           'PHS v3.5 Table 4: edition by year of the health data' AS edition_policy,
           CASE
               WHEN r.analysis_year IS NULL THEN 'missing_year'
               WHEN r.analysis_year < 1 OR r.analysis_year > 9999 THEN 'invalid_year'
               WHEN e.edition IS NULL THEN 'no_edition'
               ELSE 'ok'
           END AS edition_status
    FROM requested r
    LEFT JOIN era e ON r.analysis_year BETWEEN e.year_from AND e.year_to
),
"""
    if variant == "era":
        return f"""WITH inputs AS (
    -- STEP 1. INPUT. Replace this SELECT with: SELECT id, postcode, analysis_year FROM your_cohort
    -- analysis_year is the year of the health data as an integer, not a SIMD label.
    -- id need not be unique; every input row comes back as one output row.
    SELECT 1 AS id, CAST('AB24 2TY' AS varchar(32)) AS postcode, 2020 AS analysis_year
),
requested AS (
    -- STEP 2. KEY. Uppercase and remove ASCII spaces, keeping the original text: the same rule
    -- as ingestion (project choice). Nothing is repaired and an NRS A/B/C suffix is not
    -- removed, so supply the ordinary postcode as a person writes it.
    SELECT id, postcode, CAST(NULL AS date) AS address_date, analysis_year,
           NULLIF(UPPER(REPLACE(postcode, ' ', '')), '') AS postcode_key
    FROM inputs
),
era AS (
    -- STEP 3. EDITION. PHS v3.5 Table 4, printed p.17: the year of the health data chooses the
    -- SIMD edition, and the edition fixes the data-zone vintage. Before 1996 there is no SIMD;
    -- the guidance points to Carstairs, which this table does not carry.
    SELECT * FROM (VALUES
{table4}
    ) AS v(year_from, year_to, edition, data_zone_vintage)
),
chosen AS (
    SELECT r.id, r.postcode, r.address_date, r.analysis_year, r.postcode_key,
           e.edition AS simd_edition, e.data_zone_vintage,
           'PHS v3.5 Table 4: edition by year of the health data' AS edition_policy,
           CASE
               WHEN r.analysis_year IS NULL THEN 'missing_year'
               WHEN r.analysis_year < 1 OR r.analysis_year > 9999 THEN 'invalid_year'
               WHEN e.edition IS NULL THEN 'no_edition'
               ELSE 'ok'
           END AS edition_status
    FROM requested r
    LEFT JOIN era e ON r.analysis_year BETWEEN e.year_from AND e.year_to
),
"""
    vintages = ",\n".join(f"        ('{ed}', {v})" for ed, v in editions)
    return f"""WITH inputs AS (
    -- STEP 1. INPUT. Replace this SELECT with: SELECT id, postcode FROM your_cohort
    -- id need not be unique; every input row comes back as one output row.
    SELECT 1 AS id, CAST('AB24 2TY' AS varchar(32)) AS postcode
),
requested AS (
    -- STEP 2. KEY. Uppercase and remove ASCII spaces, keeping the original text: the same rule
    -- as ingestion (project choice). Nothing is repaired and an NRS A/B/C suffix is not
    -- removed, so supply the ordinary postcode as a person writes it.
    SELECT id, postcode, CAST(NULL AS date) AS address_date, CAST(NULL AS integer) AS analysis_year,
           NULLIF(UPPER(REPLACE(postcode, ' ', '')), '') AS postcode_key
    FROM inputs
),
study_edition AS (
    -- STEP 3. EDITION. PHS v3.5 section 3.2.1.2: one edition throughout, the one whose
    -- population year is closest to the start of what you study (Table 4, p.17). Edit the
    -- one marked line. The vintage follows from the edition; do not edit it.
    SELECT '2020v2' AS edition   -- EDIT EDITION
),
era AS (
    SELECT * FROM (VALUES
{vintages}
    ) AS v(edition, data_zone_vintage)
),
chosen AS (
    SELECT r.id, r.postcode, r.address_date, r.analysis_year, r.postcode_key,
           e.edition AS simd_edition, e.data_zone_vintage,
           'PHS v3.5 section 3.2.1.2: one edition throughout' AS edition_policy,
           CASE WHEN e.edition IS NULL THEN 'unknown_edition' ELSE 'ok' END AS edition_status
    FROM requested r
    CROSS JOIN study_edition s
    LEFT JOIN era e ON e.edition = s.edition
),
"""


def _source_columns(editions: list) -> str:
    cols = ["pc_norm AS source_pc_norm", "introduced_on AS source_introduced_on", "is_current AS source_is_current"]
    cols += [f"DataZone{v}Code AS source_dz{v}" for v in _vintages(editions)]
    cols += [f"IntermediateZone{v}Code AS source_iz{v}" for v in _vintages(editions)]
    cols += [f"phs_dz{v}_{g}" for v in _vintages(editions) for g in GEOGRAPHY]
    cols += [f"simd{ed}_{suffix}" for ed, _ in editions for _, suffix in MEASURES]
    return ",\n           ".join(cols)


def _raw_context(raw: list) -> str:
    # The matched record's own NRS fields, names unchanged except Postcode, which would collide
    # with the input column in a case-insensitive database.
    return ",\n           ".join("r.Postcode AS matched_postcode" if c == "Postcode" else f"r.{c}" for c in raw)


def _part(alias: str) -> str:
    """The NRS split suffix of a record: '' for a whole postcode, else A, B or C. Derived from
    the key and its base rather than from the last character, because whole postcodes end in
    A, B and C too (G71 8BQB is a whole postcode)."""
    return f"SUBSTRING({alias}.pc_norm, LEN({alias}.pc_base) + 1, 10)"


def _tier(alias: str) -> str:
    """Ranking tier for split resolution: the whole record ranks as A, so whole and A tie and
    the newest wins between them; then B, then C, then any later suffix in letter order."""
    return f"CASE WHEN {_part(alias)} = '' THEN 'A' ELSE {_part(alias)} END"


def _selection_spd(editions: list, raw: list) -> str:
    return f"""latest_lives AS (
    -- STEP 4. LATEST LIFE (SPD only). The directory keeps every life of a postcode. PHS's
    -- postcode file is "based on the most recent version of a postcode" and NRS's SSPL keeps
    -- "only the latest version", so take the newest introduction of each full NRS key,
    -- across both user types. A postcode that changed user type keeps its newest life only.
    -- This is not matching on an address date; use link_as_of.sql for that question.
    SELECT p.*,
           ROW_NUMBER() OVER (PARTITION BY p.pc_norm ORDER BY p.introduced_on DESC) AS life_number
    FROM postcode_simd_history p
),
latest AS (
    SELECT * FROM latest_lives WHERE life_number = 1
),
ranked AS (
    -- STEP 5. SPLIT PARTS (SPD only). An ordinary postcode can be several A/B/C rows. PHS
    -- "lookups include only the A part"; NRS uses A because it "contains more addresses".
    -- Project choice for the order: a live record first, then the whole record ranked as A,
    -- then B, then C, then the newest introduction. A postcode whose best record is a B or C
    -- part gets no SIMD (split_a_missing); two equally good records get none either
    -- (ambiguous_postcode). NRS introduces and retires the parts together, so in the current
    -- directory a B or C part has never been the only live one; the order is kept for the day
    -- it is.
    SELECT l.*,
           DENSE_RANK() OVER (
               PARTITION BY l.pc_base
               ORDER BY CASE WHEN l.is_current = 1 THEN 0 ELSE 1 END,
                        {_tier('l')},
                        l.introduced_on DESC
           ) AS priority
    FROM latest l
),
candidates AS (
    SELECT r.*,
           COUNT(*) OVER (PARTITION BY r.pc_base) AS candidate_count,
           ROW_NUMBER() OVER (PARTITION BY r.pc_base ORDER BY r.pc_norm) AS candidate_number
    FROM ranked r
    WHERE r.priority = 1
),
representative AS (
    SELECT * FROM candidates WHERE candidate_number = 1
),
geography_source AS (
    -- STEP 6a. WHO CAN SUPPLY GEOGRAPHY. Small-user records of the latest lives, addressed by
    -- their exact key. The directory keeps a linked key's A/B/C suffix, so a large user linked
    -- to "AB1 2CDB" resolves to that B part exactly, as NRS recorded it.
    SELECT pc_norm AS source_key,
           {_source_columns(editions)}
    FROM latest
    WHERE spd_user_type = 'small_user'
),
matched AS (
    -- STEP 6b. LARGE USERS. PHS v3.5 Appendix A, p.30: a large-user postcode has no boundary;
    -- where NRS could link it to a small-user postcode, that postcode supplies the geography;
    -- a PO box (NO LINKP) or an unlinked large user (NO LINK) gets none. A small user supplies
    -- its own geography. Never the large user's own zone, never another product, never a chain
    -- through a second large user. The large user's own fields stay visible as context below.
    SELECT c.*,
           r.pc_norm AS matched_pc_norm, r.introduced_on AS matched_introduced_on,
           r.is_current AS matched_is_current, r.spd_user_type AS matched_user_type,
           r.LinkedSmallUserPostcode AS requested_link_postcode,
           r.candidate_count AS matched_candidate_count, r.spd_release AS index_release,
           r.pc_base AS matched_pc_base,
           {_raw_context(raw)},
           g.*
    FROM chosen c
    LEFT JOIN representative r ON r.pc_base = c.postcode_key
    LEFT JOIN geography_source g ON g.source_key = CASE
        WHEN r.candidate_count > 1 THEN NULL
        WHEN {_part('r')} NOT IN ('', 'A') THEN NULL
        WHEN r.spd_user_type = 'small_user' THEN r.pc_norm
        ELSE UPPER(REPLACE(r.LinkedSmallUserPostcode, ' ', ''))
    END
),
"""


def _g_columns(editions: list) -> str:
    """The geography record's columns, aliased, for a join that cannot use g.* safely."""
    cols = ["g.pc_norm AS source_pc_norm", "g.introduced_on AS source_introduced_on", "g.is_current AS source_is_current"]
    cols += [f"g.DataZone{v}Code AS source_dz{v}" for v in _vintages(editions)]
    cols += [f"g.IntermediateZone{v}Code AS source_iz{v}" for v in _vintages(editions)]
    cols += [f"g.phs_dz{v}_{g}" for v in _vintages(editions) for g in GEOGRAPHY]
    cols += [f"g.simd{ed}_{suffix}" for ed, _ in editions for _, suffix in MEASURES]
    return ",\n           ".join(cols)


def _selection_spd_asof(editions: list, raw: list) -> str:
    return f"""lookup_requests AS (
    -- Resolve each postcode/date pair once, then join back to every original input row.
    -- No unique patient ID or execution-dependent row number is needed (project choice).
    SELECT DISTINCT postcode_key, address_date FROM requested
),
lives_on_date AS (
    -- STEP 4. LIFE VALID ON THE ADDRESS DATE (SPD only, project policy). A life runs from
    -- introduced_on up to but not including deleted_on. Take every life of the ordinary
    -- postcode that contains the address date. A postcode can be deleted and later re-used
    -- elsewhere; the address date decides which life the record belongs to. A record deleted
    -- on the address date is not valid on it. Same-day records are never valid. This does
    -- not reconstruct historical administrative or rurality snapshots.
    SELECT c.postcode_key AS requested_key, c.address_date AS requested_date, p.*,
           DENSE_RANK() OVER (
               PARTITION BY c.postcode_key, c.address_date
               ORDER BY {_tier('p')},
                        p.introduced_on DESC
           ) AS priority
    FROM lookup_requests c
    JOIN postcode_simd_history p
      ON p.pc_base = c.postcode_key
     AND p.introduced_on <= c.address_date
     AND (p.deleted_on IS NULL OR p.deleted_on > c.address_date)
),
candidates AS (
    -- STEP 5. SPLIT PARTS (SPD only). Among the lives valid on the date, PHS "lookups include
    -- only the A part" and NRS uses A because it "contains more addresses": the whole record
    -- ranks as A, then B, then C, then the newest introduction (project choice). A postcode
    -- whose only valid part is B or C gets split_a_missing and no SIMD; two equally good
    -- records get ambiguous_postcode and no SIMD. NRS introduces and retires the parts
    -- together, so no date in the current directory has a B or C part valid without A.
    SELECT l.*,
           COUNT(*) OVER (PARTITION BY l.requested_key, l.requested_date) AS candidate_count,
           ROW_NUMBER() OVER (PARTITION BY l.requested_key, l.requested_date ORDER BY l.pc_norm) AS candidate_number
    FROM lives_on_date l
    WHERE l.priority = 1
),
representative AS (
    SELECT * FROM candidates WHERE candidate_number = 1
),
key_lives AS (
    -- When no life contains the date, say where the date falls relative to the lives that
    -- exist: before the first life, after the last, or in a gap between two lives.
    SELECT c.postcode_key AS requested_key, c.address_date AS requested_date,
           MIN(p.introduced_on) AS first_introduced_on,
           MAX(CASE WHEN p.deleted_on IS NOT NULL AND p.deleted_on <= c.address_date THEN p.deleted_on END) AS previous_life_deleted_on,
           MIN(CASE WHEN p.introduced_on > c.address_date THEN p.introduced_on END) AS next_life_introduced_on
    FROM lookup_requests c
    JOIN postcode_simd_history p ON p.pc_base = c.postcode_key
    GROUP BY c.postcode_key, c.address_date
),
matched AS (
    -- STEP 6. LARGE USERS. PHS v3.5 Appendix A, p.30: a large-user postcode has no boundary;
    -- where NRS could link it to a small-user postcode, that postcode supplies the geography;
    -- a PO box (NO LINKP) or an unlinked large user (NO LINK) gets none. The linked small-user
    -- record must itself be valid on the address date (project policy), by its exact key
    -- including any A/B/C suffix. A small user supplies its own geography. Never the large
    -- user's own zone, another product, or a chain through a second large user.
    SELECT c.*,
           r.pc_norm AS matched_pc_norm, r.introduced_on AS matched_introduced_on,
           r.is_current AS matched_is_current, r.spd_user_type AS matched_user_type,
           r.LinkedSmallUserPostcode AS requested_link_postcode,
           r.candidate_count AS matched_candidate_count, r.spd_release AS index_release,
           r.pc_base AS matched_pc_base,
           k.first_introduced_on, k.previous_life_deleted_on, k.next_life_introduced_on,
           {_raw_context(raw)},
           {_g_columns(editions)}
    FROM chosen c
    LEFT JOIN representative r ON r.requested_key = c.postcode_key AND r.requested_date = c.address_date
    LEFT JOIN key_lives k ON k.requested_key = c.postcode_key
                        AND (k.requested_date = c.address_date
                             OR (k.requested_date IS NULL AND c.address_date IS NULL))
    LEFT JOIN postcode_simd_history g
      ON g.spd_user_type = 'small_user'
     AND g.pc_norm = CASE
             WHEN r.candidate_count > 1 THEN NULL
             WHEN {_part('r')} NOT IN ('', 'A') THEN NULL
             WHEN r.spd_user_type = 'small_user' THEN r.pc_norm
             ELSE UPPER(REPLACE(r.LinkedSmallUserPostcode, ' ', ''))
         END
     AND g.introduced_on <= c.address_date
     AND (g.deleted_on IS NULL OR g.deleted_on > c.address_date)
),
"""


def _selection_sspl(editions: list, raw: list) -> str:
    return f"""-- STEPS 4 AND 5 ARE NOT NEEDED. NRS built the SSPL with "only the latest version" of each
-- postcode and made split postcodes whole: "the original A part of the split postcode is
-- used" and the counts are combined (NRS SSPL information note). One row per postcode,
-- key pc_norm, so the postcode key joins directly. Deleted latest lives are present and are
-- reported through matched_is_current, not removed.
geography_source AS (
    -- STEP 6a. WHO CAN SUPPLY GEOGRAPHY. Small-user records, addressed by their whole key.
    -- NRS keeps a linked key's A suffix in the SSPL although the small-user row is whole, so a
    -- record flagged SplitIndicator = Y is also addressable by its key plus 'A' (project
    -- reading of the SSPL dictionary). A B or C suffix cannot resolve: those parts' geography
    -- is not in the SSPL. A whole key cannot collide with a key plus 'A'.
    SELECT pc_norm AS source_key,
           {_source_columns(editions)}
    FROM postcode_simd
    WHERE spd_user_type = 'small_user'
    UNION ALL
    SELECT CONCAT(pc_norm, 'A') AS source_key,
           {_source_columns(editions)}
    FROM postcode_simd
    WHERE spd_user_type = 'small_user' AND SplitIndicator = 'Y'
),
matched AS (
    -- STEP 6b. LARGE USERS. Project interpretation of PHS v3.5 Appendix A, p.30: use the
    -- linked small user's geography; no SIMD for PO boxes (NO LINKP) or unlinked large users
    -- (NO LINK). Appendix A does not explicitly settle overriding SSPL's own allocated zone.
    -- We retain this policy pending confirmation; the large user's own fields remain context.
    -- A small user supplies its own geography. No cross-product fallback or large-user chain.
    SELECT c.*,
           r.pc_norm AS matched_pc_norm, r.introduced_on AS matched_introduced_on,
           r.is_current AS matched_is_current, r.spd_user_type AS matched_user_type,
           r.LinkedSmallUserPostcode AS requested_link_postcode,
           r.sspl_release AS index_release,
           {_raw_context(raw)},
           g.*
    FROM chosen c
    LEFT JOIN postcode_simd r ON r.pc_norm = c.postcode_key
    LEFT JOIN geography_source g ON g.source_key = CASE
        WHEN r.spd_user_type = 'small_user' THEN r.pc_norm
        ELSE UPPER(REPLACE(r.LinkedSmallUserPostcode, ' ', ''))
    END
),
"""


def _values_and_report(name: str, p: dict, editions: list, raw: list, variant: str = "era") -> str:
    vintages = _vintages(editions)
    selects = [_case("m.data_zone_vintage", [(v, f"m.source_dz{v}") for v in vintages], "data_zone_code", quote=False),
               _case("m.data_zone_vintage", [(v, f"m.source_iz{v}") for v in vintages], "intermediate_zone_code", quote=False)]
    for g in GEOGRAPHY:
        selects.append(_case("m.data_zone_vintage", [(v, f"m.phs_dz{v}_{g}") for v in vintages], f"phs_{g}_code", quote=False))
    for out, suffix in MEASURES:
        selects.append(_case("m.simd_edition", [(ed, f"m.simd{ed}_{suffix}") for ed, _ in editions], out))
    measures = ",\n".join(selects)
    nulls = " OR ".join([f"s.{out} IS NULL" for out, _ in MEASURES] + ["s.data_zone_code IS NULL"]
                        + [f"s.phs_{g}_code IS NULL" for g in GEOGRAPHY])
    if name == "spd" and variant == "asof":
        postcode_status = """           CASE
               WHEN s.postcode_key IS NULL THEN 'missing_postcode'
               WHEN s.first_introduced_on IS NULL THEN 'not_found'
               WHEN s.matched_pc_norm IS NULL AND s.address_date IS NULL THEN 'missing_address_date'
               WHEN s.matched_pc_norm IS NULL AND s.address_date < s.first_introduced_on THEN 'postcode_not_yet_introduced'
               WHEN s.matched_pc_norm IS NULL AND s.next_life_introduced_on IS NOT NULL THEN 'between_lives'
               WHEN s.matched_pc_norm IS NULL THEN 'postcode_deleted_by_date'
               WHEN s.matched_candidate_count > 1 THEN 'ambiguous_postcode'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) NOT IN ('', 'A') THEN 'split_a_missing'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) = 'NOLINKP' THEN 'po_box'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) IN ('', 'NOLINK') THEN 'unlinked_large_user'
               WHEN s.source_pc_norm IS NULL THEN 'linked_small_user_not_found'
               WHEN s.matched_user_type = 'large_user' THEN 'linked_small_user'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) = 'A' THEN 'a_part'
               ELSE 'matched'
           END AS postcode_status"""
        extra_context = ("s.first_introduced_on, s.previous_life_deleted_on, s.next_life_introduced_on,\n       "
                         "s.matched_pc_base,\n       ")
    elif name == "spd":
        postcode_status = """           CASE
               WHEN s.postcode_key IS NULL THEN 'missing_postcode'
               WHEN s.matched_pc_norm IS NULL THEN 'not_found'
               WHEN s.matched_candidate_count > 1 THEN 'ambiguous_postcode'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) NOT IN ('', 'A') THEN 'split_a_missing'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) = 'NOLINKP' THEN 'po_box'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) IN ('', 'NOLINK') THEN 'unlinked_large_user'
               WHEN s.source_pc_norm IS NULL THEN 'linked_small_user_not_found'
               WHEN s.matched_user_type = 'large_user' THEN 'linked_small_user'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) = 'A' THEN 'a_part'
               ELSE 'matched'
           END AS postcode_status"""
        extra_context = "s.matched_pc_base,\n       "
    else:
        postcode_status = """           CASE
               WHEN s.postcode_key IS NULL THEN 'missing_postcode'
               WHEN s.matched_pc_norm IS NULL THEN 'not_found'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) = 'NOLINKP' THEN 'po_box'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) IN ('', 'NOLINK') THEN 'unlinked_large_user'
               WHEN s.source_pc_norm IS NULL THEN 'linked_small_user_not_found'
               WHEN s.matched_user_type = 'large_user' THEN 'linked_small_user'
               WHEN s.SplitIndicator = 'Y' THEN 'a_part'
               ELSE 'matched'
           END AS postcode_status"""
        extra_context = ""
    context = ",\n       ".join("s.matched_postcode" if c == "Postcode" else f"s.{c}" for c in raw)
    out_measures = ",\n       ".join(f"s.{out}" for out, _ in MEASURES)
    return f"""selected AS (
    -- STEP 7. VALUES. Copy the stored values of the chosen edition from the record that
    -- supplies the geography, through the data zone of that edition's vintage (PHS Table 4:
    -- 2001 zones for 2004 to 2012, 2011 zones for 2016 and 2020v2). The intermediate zone of
    -- the same vintage, which nests those data zones, comes with it. The three PHS codes are the
    -- areas PHS used for the within-board, within-HSCP and within-council bands (section 3.4):
    -- use them, not the NRS administrative codes, with those bands. Every one of the 14
    -- stored measures is copied: PHS population-weighted bands and flags (pw), Scottish
    -- Government unweighted bands (uw); never mix the two in one analysis (sections 3.1.2,
    -- 3.3). Band 1 is most deprived in every edition; ingestion already reversed the 2004 and
    -- 2006 PHS bands, so nothing is reversed here.
    SELECT m.*,
{measures},
           '1 = most deprived' AS band_direction
    FROM matched m
),
reported AS (
    -- STEP 8a. POSTCODE STATUS. What happened to the postcode, independent of the year.
    SELECT s.*,
{postcode_status}
    FROM selected s
)
SELECT
    -- STEP 8b. REPORT. One row per input row. simd_status says whether the SIMD columns can be
    -- used: a year problem first, then a postcode problem, then a missing stored value.
    -- Product provenance and both keys are returned so the route can be reviewed
    -- (PHS checklist, p.25: state index, edition, weighting, direction and level).
       s.id, s.postcode, s.address_date, s.analysis_year, s.postcode_key,
       s.postcode_status,
       CASE
           WHEN s.edition_status <> 'ok' THEN s.edition_status
           WHEN s.postcode_status NOT IN ('matched', 'a_part', 'linked_small_user') THEN s.postcode_status
           WHEN {nulls} THEN 'missing_simd'
           ELSE 'matched'
       END AS simd_status,
       '{p['index_source']}' AS index_source, s.index_release, '{p['allocation']}' AS allocation,
       s.simd_edition, s.edition_policy, s.data_zone_vintage,
       s.matched_pc_norm, s.matched_introduced_on, s.matched_is_current, s.matched_user_type,
       s.requested_link_postcode,
       s.source_pc_norm AS simd_source_pc_norm, s.source_introduced_on AS simd_source_introduced_on,
       s.source_is_current AS simd_source_is_current,
       s.data_zone_code, s.intermediate_zone_code, s.phs_hb_code, s.phs_hscp_code, s.phs_ca_code,
       {out_measures},
       s.band_direction,
       -- Own-record context: the matched record's NRS fields as ingested, names unchanged
       -- (Postcode as matched_postcode). For a large user these are its own fields, not the
       -- linked small user's; compare DataZone2011Code here with simd_source_pc_norm above.
       -- link_as_of.sql first gives the nearest lives when no life contains the address date.
       {extra_context}{context}
FROM reported s;
"""


def render(name: str, variant: str) -> str:
    p = PRODUCTS[name]
    registry = load_registry(PACKAGE / "sources.yaml")
    editions = _editions(registry)
    schema = yaml.safe_load((PACKAGE / p["schema"]).read_text())
    # The export contract decides what leaves the build, so a linkage result carries the same
    # fields the CSV does. The Parquet keeps them all for anyone who needs them internally.
    excluded = set(load_contract(PACKAGE / "export_contract.yaml")["tables"][p["contract_table"]]["exclude"])
    raw = [f["name"] for f in schema["fields"] if f["source"] == p["raw_source"] and f["name"] not in excluded]
    if variant == "asof":
        if name != "spd":
            raise ValueError("Only the SPD set can answer a dated question: the SSPL holds one life per postcode")
        return (_header(name, p, variant) + "\n" + _inputs_and_edition(variant, editions)
                + _selection_spd_asof(editions, raw) + _values_and_report(name, p, editions, raw, variant))
    selection = _selection_spd(editions, raw) if name == "spd" else _selection_sspl(editions, raw)
    return (_header(name, p, variant) + "\n" + _inputs_and_edition(variant, editions)
            + SHARED_BEGIN + "\n" + selection + _values_and_report(name, p, editions, raw, variant).rstrip("\n")
            + "\n" + SHARED_END + "\n")


def shared_block(text: str) -> str:
    return text.split(SHARED_BEGIN, 1)[1].split(SHARED_END, 1)[0]


def main(argv=None) -> int:
    out = Path(argv[0]) if argv else ROOT / "docs" / "sql"
    for name in PRODUCTS:
        (out / name).mkdir(parents=True, exist_ok=True)
        for variant in FILES[name]:
            path = out / name / VARIANTS[variant]
            path.write_text(render(name, variant))
            print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
