-- SPD SET, Scottish Postcode Directory (SPD): the postcode LIFE VALID ON THE ADDRESS DATE, edition by the year of the health data.
-- Reads postcode_simd_history, imported from results/postcode_simd_history.parquet with its natural key (pc_norm, introduced_on).
-- Standalone: no view, no other script, no other postcode product. Nothing is recalculated.
-- NRS did upstream: nothing: every life of every postcode is a row, and split postcodes are A/B/C rows.
-- Steps are numbered; each names the guidance it follows or says it is a project choice.
-- Guidance: PHS deprivation guidance v3.5 (Table 4 p.17, sections 3.1 to 3.4, Appendix A
-- pp.28-30), the PHS postcode-file page, the NRS SSPL information note and NRS dictionaries.
-- Executed on DuckDB and on SQL Server 2022; see ../LINKAGE_BY_ERA.md for the import recipe.
-- Columns named in export_contract.yaml are not returned; the Parquet keeps them.
-- Generated by python -m simd_ingest.sql_examples from the schemas; edit the generator.

WITH inputs AS (
    -- STEP 1. INPUT. Replace this SELECT with:
    --   SELECT id, postcode, address_date, CAST(NULL AS int) AS analysis_year FROM your_cohort
    -- address_date must relate to this person's address; do not assume a general record edit
    -- date is a residence date. Selecting a life on that date is a project policy. For an
    -- SMR01 episode the admission date is both the address date and the year of the event.
    -- analysis_year is an OVERRIDE, and null is the normal case: leave it null and the SIMD
    -- edition comes from the year of the address date. Set it to one constant for every row to
    -- hold a single edition across a whole trend, which PHS v3.5 section 3.2.1.2 describes.
    -- This row derives its edition: 2005 selects SIMD 2006, and the address date selects the
    -- life this postcode had then, which is not its current one.
    SELECT 1 AS id, CAST('AB11 5FA' AS varchar(32)) AS postcode,
           CAST('2005-06-10' AS date) AS address_date, CAST(NULL AS int) AS analysis_year
),
requested AS (
    -- STEP 2. KEY. Uppercase and remove ASCII spaces, keeping the original text: the same rule
    -- as ingestion (project choice). Nothing is repaired and an NRS A/B/C suffix is not
    -- removed, so supply the ordinary postcode as a person writes it. Duplicate inputs stay.
    SELECT id, postcode, address_date,
           -- The override, or the year the address date falls in. One input covers the usual
           -- case; the reported analysis_year below is whichever was used.
           COALESCE(analysis_year, YEAR(address_date)) AS analysis_year,
           NULLIF(UPPER(REPLACE(postcode, ' ', '')), '') AS postcode_key
    FROM inputs
),
era AS (
    -- STEP 3. EDITION. PHS v3.5 Table 4, printed p.17: the year of the health data chooses the
    -- SIMD edition, and the edition fixes the data-zone vintage. Before 1996 there is no SIMD;
    -- the guidance points to Carstairs, which this table does not carry.
    SELECT * FROM (VALUES
        (1996, 2003, '2004', 2001),
        (2004, 2006, '2006', 2001),
        (2007, 2009, '2009v2', 2001),
        (2010, 2013, '2012', 2001),
        (2014, 2016, '2016', 2011),
        (2017, 9999, '2020v2', 2011)
    ) AS v(year_from, year_to, edition, data_zone_vintage)
),
rurality_era AS (
    -- STEP 3b. RURALITY VERSION (SPD only). PROJECT CHOICE: there is no PHS table for this.
    -- The Scottish Government Urban Rural Classification version is chosen by its REFERENCE
    -- year, the year it describes, not the date it was published: the 2022 version describes
    -- Census Day 2022 and appeared on 16 December 2024. A version applies until the year before
    -- the next one. Before 2003 there is no version. The year is the same year that chose the
    -- SIMD edition, so an overriding analysis_year holds the classification fixed as well.
    SELECT * FROM (VALUES
        (2003, 2004, '2003-2004'),
        (2005, 2006, '2005-2006'),
        (2007, 2008, '2007-2008'),
        (2009, 2010, '2009-2010'),
        (2011, 2012, '2011-2012'),
        (2013, 2015, '2013-2014'),
        (2016, 2019, '2016'),
        (2020, 2021, '2020'),
        (2022, 9999, '2022')
    ) AS v(year_from, year_to, version)
),
chosen AS (
    SELECT r.id, r.postcode, r.address_date, r.analysis_year, r.postcode_key,
           e.edition AS simd_edition, e.data_zone_vintage,
           'PHS v3.5 Table 4: edition by year of the health data' AS edition_policy,
           CASE
               WHEN r.analysis_year IS NULL THEN 'missing_year'
               WHEN r.analysis_year < 1 OR r.analysis_year > 9999 THEN 'invalid_year'
               WHEN e.edition IS NULL THEN 'no_edition'
               ELSE 'ok'
           END AS edition_status,
           u.version AS rurality_version,
           'project choice: classification version by reference year of the health data' AS rurality_policy
    FROM requested r
    LEFT JOIN era e ON r.analysis_year BETWEEN e.year_from AND e.year_to
    LEFT JOIN rurality_era u ON r.analysis_year BETWEEN u.year_from AND u.year_to
),
lookup_requests AS (
    -- Resolve each postcode/date pair once, then join back to every original input row.
    -- No unique patient ID or execution-dependent row number is needed (project choice).
    SELECT DISTINCT postcode_key, address_date FROM requested
),
lives_on_date AS (
    -- STEP 4. LIFE VALID ON THE ADDRESS DATE (SPD only, project policy). A life runs from
    -- introduced_on up to but not including deleted_on. Take every life of the ordinary
    -- postcode that contains the address date. A postcode can be deleted and later re-used
    -- elsewhere; the address date decides which life the record belongs to. A record deleted
    -- on the address date is not valid on it. Same-day records are never valid. This does
    -- not reconstruct historical administrative snapshots; the one historical classification
    -- returned, rurality, is chosen by year in step 3b and read from the life selected here.
    SELECT c.postcode_key AS requested_key, c.address_date AS requested_date, p.*,
           DENSE_RANK() OVER (
               PARTITION BY c.postcode_key, c.address_date
               ORDER BY CASE WHEN SUBSTRING(p.pc_norm, LEN(p.pc_base) + 1, 10) = '' THEN 'A' ELSE SUBSTRING(p.pc_norm, LEN(p.pc_base) + 1, 10) END,
                        p.introduced_on DESC
           ) AS priority
    FROM lookup_requests c
    JOIN postcode_simd_history p
      ON p.pc_base = c.postcode_key
     AND p.introduced_on <= c.address_date
     AND (p.deleted_on IS NULL OR p.deleted_on > c.address_date)
),
candidates AS (
    -- STEP 5. SPLIT PARTS (SPD only). Among the lives valid on the date, PHS "lookups include
    -- only the A part" and NRS uses A because it "contains more addresses": the whole record
    -- ranks as A, then B, then C, then the newest introduction (project choice). A postcode
    -- whose only valid part is B or C gets split_a_missing and no SIMD; two equally good
    -- records get ambiguous_postcode and no SIMD. NRS introduces and retires the parts
    -- together, so no date in the current directory has a B or C part valid without A.
    SELECT l.*,
           COUNT(*) OVER (PARTITION BY l.requested_key, l.requested_date) AS candidate_count,
           ROW_NUMBER() OVER (PARTITION BY l.requested_key, l.requested_date ORDER BY l.pc_norm) AS candidate_number
    FROM lives_on_date l
    WHERE l.priority = 1
),
representative AS (
    SELECT * FROM candidates WHERE candidate_number = 1
),
key_lives AS (
    -- When no life contains the date, say where the date falls relative to the lives that
    -- exist: before the first life, after the last, or in a gap between two lives.
    SELECT c.postcode_key AS requested_key, c.address_date AS requested_date,
           MIN(p.introduced_on) AS first_introduced_on,
           MAX(CASE WHEN p.deleted_on IS NOT NULL AND p.deleted_on <= c.address_date THEN p.deleted_on END) AS previous_life_deleted_on,
           MIN(CASE WHEN p.introduced_on > c.address_date THEN p.introduced_on END) AS next_life_introduced_on
    FROM lookup_requests c
    JOIN postcode_simd_history p ON p.pc_base = c.postcode_key
    GROUP BY c.postcode_key, c.address_date
),
matched AS (
    -- STEP 6. LARGE USERS. PHS v3.5 Appendix A, p.30: a large-user postcode has no boundary;
    -- where NRS could link it to a small-user postcode, that postcode supplies the geography;
    -- a PO box (NO LINKP) or an unlinked large user (NO LINK) gets none. The linked small-user
    -- record must itself be valid on the address date (project policy), by its exact key
    -- including any A/B/C suffix. A small user supplies its own geography. Never the large
    -- user's own zone, another product, or a chain through a second large user.
    SELECT c.*,
           r.pc_norm AS matched_pc_norm, r.introduced_on AS matched_introduced_on,
           r.is_current AS matched_is_current, r.spd_user_type AS matched_user_type,
           r.LinkedSmallUserPostcode AS requested_link_postcode,
           r.candidate_count AS matched_candidate_count, r.spd_release AS index_release,
           r.pc_base AS matched_pc_base,
           k.first_introduced_on, k.previous_life_deleted_on, k.next_life_introduced_on,
           r.Postcode AS matched_postcode,
           r.PostcodeDistrict,
           r.PostcodeSector,
           r.DateOfIntroduction,
           r.DateOfDeletion,
           r.SplitIndicator,
           r.CouncilArea2019Code,
           r.UKParliamentaryConstituency2024Code,
           r.ScottishParliamentaryRegion2026Code,
           r.ScottishParliamentaryConstituency2026Code,
           r.ElectoralWard2022Code,
           r.HealthBoardArea2019Code,
           r.HealthBoardArea2006Code,
           r.HealthBoardArea1995Code,
           r.IntegrationAuthority2019Code,
           r.OutputArea2022Code,
           r.OutputArea2011Code,
           r.OutputArea2001Code,
           r.OutputArea1991Code,
           r.DataZone2022Code,
           r.DataZone2011Code,
           r.DataZone2001Code,
           r.IntermediateZone2022Code,
           r.IntermediateZone2011Code,
           r.IntermediateZone2001Code,
           r.CensusHouseholdCount2022,
           r.CensusPopulationCount2022,
           r.CensusHouseholdCount2011,
           r.CensusPopulationCount2011,
           r.CensusHouseholdCount2001,
           r.CensusPopulationCount2001,
           r.CensusHouseholdCount1991,
           r.CensusPopulationCount1991,
           r.ScottishIndexOfMultipleDeprivation2020Rank,
           r.LAU2025Level1Code,
           r.ITL2025Level2Code,
           r.ITL2025Level3Code,
           r.Locality2020Code,
           r.Locality2022Code,
           r.Locality2001Code,
           r.Locality1991Code,
           r.Settlement2020Code,
           r.Settlement2022Code,
           r.Settlement2001Code,
           r.CivilParish1930Code,
           r.EnterpriseRegion2008Code,
           r.IslandCode,
           r.LocalGovernmentDistrict1995Code,
           r.LocalGovernmentDistrict1991Code,
           r.NationalPark2010Code,
           r.RegistrationDistrict2007Code,
           r.ROACommunityPlanningPartnership2006Code,
           r.ROALocal2006Code,
           r.StrategicDevelopmentPlanningArea2013Code,
           r.TravelToWorkArea2011Code,
           r.UrbanRural6Fold2022Code,
           r.UrbanRural8Fold2022Code,
           r.GridLinkIndicator,
           r.GridLinkPositionalAccuracy,
           r.NeverDigitised,
           r.LinkedSmallUserPostcode,
           r.urbanrural2003_2004_6fold,
           r.urbanrural2003_2004_8fold,
           r.urbanrural2003_2004_status,
           r.urbanrural2005_2006_6fold,
           r.urbanrural2005_2006_8fold,
           r.urbanrural2005_2006_status,
           r.urbanrural2007_2008_6fold,
           r.urbanrural2007_2008_8fold,
           r.urbanrural2007_2008_status,
           r.urbanrural2009_2010_6fold,
           r.urbanrural2009_2010_8fold,
           r.urbanrural2009_2010_status,
           r.urbanrural2011_2012_6fold,
           r.urbanrural2011_2012_8fold,
           r.urbanrural2011_2012_status,
           r.urbanrural2013_2014_6fold,
           r.urbanrural2013_2014_8fold,
           r.urbanrural2013_2014_status,
           r.urbanrural2016_6fold,
           r.urbanrural2016_8fold,
           r.urbanrural2016_status,
           r.urbanrural2020_6fold,
           r.urbanrural2020_8fold,
           r.urbanrural2020_status,
           r.urbanrural2022_6fold,
           r.urbanrural2022_8fold,
           r.urbanrural2022_status,
           g.pc_norm AS source_pc_norm,
           g.introduced_on AS source_introduced_on,
           g.is_current AS source_is_current,
           g.DataZone2001Code AS source_dz2001,
           g.DataZone2011Code AS source_dz2011,
           g.IntermediateZone2001Code AS source_iz2001,
           g.IntermediateZone2011Code AS source_iz2011,
           g.phs_dz2001_hb,
           g.phs_dz2001_hscp,
           g.phs_dz2001_ca,
           g.phs_dz2011_hb,
           g.phs_dz2011_hscp,
           g.phs_dz2011_ca,
           g.simd2004_rank,
           g.simd2004_pw_scotland_quintile,
           g.simd2004_pw_scotland_decile,
           g.simd2004_pw_hb_quintile,
           g.simd2004_pw_hb_decile,
           g.simd2004_pw_hscp_quintile,
           g.simd2004_pw_hscp_decile,
           g.simd2004_pw_ca_quintile,
           g.simd2004_pw_ca_decile,
           g.simd2004_most15pc,
           g.simd2004_least15pc,
           g.simd2004_uw_scotland_quintile,
           g.simd2004_uw_scotland_decile,
           g.simd2004_uw_scotland_vigintile,
           g.simd2006_rank,
           g.simd2006_pw_scotland_quintile,
           g.simd2006_pw_scotland_decile,
           g.simd2006_pw_hb_quintile,
           g.simd2006_pw_hb_decile,
           g.simd2006_pw_hscp_quintile,
           g.simd2006_pw_hscp_decile,
           g.simd2006_pw_ca_quintile,
           g.simd2006_pw_ca_decile,
           g.simd2006_most15pc,
           g.simd2006_least15pc,
           g.simd2006_uw_scotland_quintile,
           g.simd2006_uw_scotland_decile,
           g.simd2006_uw_scotland_vigintile,
           g.simd2009v2_rank,
           g.simd2009v2_pw_scotland_quintile,
           g.simd2009v2_pw_scotland_decile,
           g.simd2009v2_pw_hb_quintile,
           g.simd2009v2_pw_hb_decile,
           g.simd2009v2_pw_hscp_quintile,
           g.simd2009v2_pw_hscp_decile,
           g.simd2009v2_pw_ca_quintile,
           g.simd2009v2_pw_ca_decile,
           g.simd2009v2_most15pc,
           g.simd2009v2_least15pc,
           g.simd2009v2_uw_scotland_quintile,
           g.simd2009v2_uw_scotland_decile,
           g.simd2009v2_uw_scotland_vigintile,
           g.simd2012_rank,
           g.simd2012_pw_scotland_quintile,
           g.simd2012_pw_scotland_decile,
           g.simd2012_pw_hb_quintile,
           g.simd2012_pw_hb_decile,
           g.simd2012_pw_hscp_quintile,
           g.simd2012_pw_hscp_decile,
           g.simd2012_pw_ca_quintile,
           g.simd2012_pw_ca_decile,
           g.simd2012_most15pc,
           g.simd2012_least15pc,
           g.simd2012_uw_scotland_quintile,
           g.simd2012_uw_scotland_decile,
           g.simd2012_uw_scotland_vigintile,
           g.simd2016_rank,
           g.simd2016_pw_scotland_quintile,
           g.simd2016_pw_scotland_decile,
           g.simd2016_pw_hb_quintile,
           g.simd2016_pw_hb_decile,
           g.simd2016_pw_hscp_quintile,
           g.simd2016_pw_hscp_decile,
           g.simd2016_pw_ca_quintile,
           g.simd2016_pw_ca_decile,
           g.simd2016_most15pc,
           g.simd2016_least15pc,
           g.simd2016_uw_scotland_quintile,
           g.simd2016_uw_scotland_decile,
           g.simd2016_uw_scotland_vigintile,
           g.simd2020v2_rank,
           g.simd2020v2_pw_scotland_quintile,
           g.simd2020v2_pw_scotland_decile,
           g.simd2020v2_pw_hb_quintile,
           g.simd2020v2_pw_hb_decile,
           g.simd2020v2_pw_hscp_quintile,
           g.simd2020v2_pw_hscp_decile,
           g.simd2020v2_pw_ca_quintile,
           g.simd2020v2_pw_ca_decile,
           g.simd2020v2_most15pc,
           g.simd2020v2_least15pc,
           g.simd2020v2_uw_scotland_quintile,
           g.simd2020v2_uw_scotland_decile,
           g.simd2020v2_uw_scotland_vigintile
    FROM chosen c
    LEFT JOIN representative r ON r.requested_key = c.postcode_key AND r.requested_date = c.address_date
    LEFT JOIN key_lives k ON k.requested_key = c.postcode_key
                        AND (k.requested_date = c.address_date
                             OR (k.requested_date IS NULL AND c.address_date IS NULL))
    LEFT JOIN postcode_simd_history g
      ON g.spd_user_type = 'small_user'
     AND g.pc_norm = CASE
             WHEN r.candidate_count > 1 THEN NULL
             WHEN SUBSTRING(r.pc_norm, LEN(r.pc_base) + 1, 10) NOT IN ('', 'A') THEN NULL
             WHEN r.spd_user_type = 'small_user' THEN r.pc_norm
             ELSE UPPER(REPLACE(r.LinkedSmallUserPostcode, ' ', ''))
         END
     AND g.introduced_on <= c.address_date
     AND (g.deleted_on IS NULL OR g.deleted_on > c.address_date)
),
selected AS (
    -- STEP 7. VALUES. Copy the stored values of the chosen edition from the record that
    -- supplies the geography, through the data zone of that edition's vintage (PHS Table 4:
    -- 2001 zones for 2004 to 2012, 2011 zones for 2016 and 2020v2). The intermediate zone of
    -- the same vintage, which nests those data zones, comes with it. The three PHS codes are the
    -- areas PHS used for the within-board, within-HSCP and within-council bands (section 3.4):
    -- use them, not the NRS administrative codes, with those bands. Every one of the 14
    -- stored measures is copied: PHS population-weighted bands and flags (pw), Scottish
    -- Government unweighted bands (uw); never mix the two in one analysis (sections 3.1.2,
    -- 3.3). Band 1 is most deprived in every edition; ingestion already reversed the 2004 and
    -- 2006 PHS bands, so nothing is reversed here.
    SELECT m.*,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.source_dz2001
               WHEN 2011     THEN m.source_dz2011
           END AS data_zone_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.source_iz2001
               WHEN 2011     THEN m.source_iz2011
           END AS intermediate_zone_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_hb
               WHEN 2011     THEN m.phs_dz2011_hb
           END AS phs_hb_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_hscp
               WHEN 2011     THEN m.phs_dz2011_hscp
           END AS phs_hscp_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_ca
               WHEN 2011     THEN m.phs_dz2011_ca
           END AS phs_ca_code,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_rank
               WHEN '2006'   THEN m.simd2006_rank
               WHEN '2009v2' THEN m.simd2009v2_rank
               WHEN '2012'   THEN m.simd2012_rank
               WHEN '2016'   THEN m.simd2016_rank
               WHEN '2020v2' THEN m.simd2020v2_rank
           END AS simd_rank,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_scotland_quintile
               WHEN '2006'   THEN m.simd2006_pw_scotland_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_scotland_quintile
               WHEN '2012'   THEN m.simd2012_pw_scotland_quintile
               WHEN '2016'   THEN m.simd2016_pw_scotland_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_scotland_quintile
           END AS phs_pw_scotland_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_scotland_decile
               WHEN '2006'   THEN m.simd2006_pw_scotland_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_scotland_decile
               WHEN '2012'   THEN m.simd2012_pw_scotland_decile
               WHEN '2016'   THEN m.simd2016_pw_scotland_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_scotland_decile
           END AS phs_pw_scotland_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hb_quintile
               WHEN '2006'   THEN m.simd2006_pw_hb_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_hb_quintile
               WHEN '2012'   THEN m.simd2012_pw_hb_quintile
               WHEN '2016'   THEN m.simd2016_pw_hb_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_hb_quintile
           END AS phs_pw_hb_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hb_decile
               WHEN '2006'   THEN m.simd2006_pw_hb_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_hb_decile
               WHEN '2012'   THEN m.simd2012_pw_hb_decile
               WHEN '2016'   THEN m.simd2016_pw_hb_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_hb_decile
           END AS phs_pw_hb_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hscp_quintile
               WHEN '2006'   THEN m.simd2006_pw_hscp_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_hscp_quintile
               WHEN '2012'   THEN m.simd2012_pw_hscp_quintile
               WHEN '2016'   THEN m.simd2016_pw_hscp_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_hscp_quintile
           END AS phs_pw_hscp_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hscp_decile
               WHEN '2006'   THEN m.simd2006_pw_hscp_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_hscp_decile
               WHEN '2012'   THEN m.simd2012_pw_hscp_decile
               WHEN '2016'   THEN m.simd2016_pw_hscp_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_hscp_decile
           END AS phs_pw_hscp_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_ca_quintile
               WHEN '2006'   THEN m.simd2006_pw_ca_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_ca_quintile
               WHEN '2012'   THEN m.simd2012_pw_ca_quintile
               WHEN '2016'   THEN m.simd2016_pw_ca_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_ca_quintile
           END AS phs_pw_ca_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_ca_decile
               WHEN '2006'   THEN m.simd2006_pw_ca_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_ca_decile
               WHEN '2012'   THEN m.simd2012_pw_ca_decile
               WHEN '2016'   THEN m.simd2016_pw_ca_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_ca_decile
           END AS phs_pw_ca_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_most15pc
               WHEN '2006'   THEN m.simd2006_most15pc
               WHEN '2009v2' THEN m.simd2009v2_most15pc
               WHEN '2012'   THEN m.simd2012_most15pc
               WHEN '2016'   THEN m.simd2016_most15pc
               WHEN '2020v2' THEN m.simd2020v2_most15pc
           END AS phs_pw_most15pc,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_least15pc
               WHEN '2006'   THEN m.simd2006_least15pc
               WHEN '2009v2' THEN m.simd2009v2_least15pc
               WHEN '2012'   THEN m.simd2012_least15pc
               WHEN '2016'   THEN m.simd2016_least15pc
               WHEN '2020v2' THEN m.simd2020v2_least15pc
           END AS phs_pw_least15pc,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_quintile
               WHEN '2006'   THEN m.simd2006_uw_scotland_quintile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_quintile
               WHEN '2012'   THEN m.simd2012_uw_scotland_quintile
               WHEN '2016'   THEN m.simd2016_uw_scotland_quintile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_quintile
           END AS gov_uw_scotland_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_decile
               WHEN '2006'   THEN m.simd2006_uw_scotland_decile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_decile
               WHEN '2012'   THEN m.simd2012_uw_scotland_decile
               WHEN '2016'   THEN m.simd2016_uw_scotland_decile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_decile
           END AS gov_uw_scotland_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_vigintile
               WHEN '2006'   THEN m.simd2006_uw_scotland_vigintile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_vigintile
               WHEN '2012'   THEN m.simd2012_uw_scotland_vigintile
               WHEN '2016'   THEN m.simd2016_uw_scotland_vigintile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_vigintile
           END AS gov_uw_scotland_vigintile,
           CASE m.rurality_version
               WHEN '2003-2004' THEN m.urbanrural2003_2004_6fold
               WHEN '2005-2006' THEN m.urbanrural2005_2006_6fold
               WHEN '2007-2008' THEN m.urbanrural2007_2008_6fold
               WHEN '2009-2010' THEN m.urbanrural2009_2010_6fold
               WHEN '2011-2012' THEN m.urbanrural2011_2012_6fold
               WHEN '2013-2014' THEN m.urbanrural2013_2014_6fold
               WHEN '2016'   THEN m.urbanrural2016_6fold
               WHEN '2020'   THEN m.urbanrural2020_6fold
               WHEN '2022'   THEN m.urbanrural2022_6fold
           END AS rurality_6fold_stored,
           CASE m.rurality_version
               WHEN '2003-2004' THEN m.urbanrural2003_2004_8fold
               WHEN '2005-2006' THEN m.urbanrural2005_2006_8fold
               WHEN '2007-2008' THEN m.urbanrural2007_2008_8fold
               WHEN '2009-2010' THEN m.urbanrural2009_2010_8fold
               WHEN '2011-2012' THEN m.urbanrural2011_2012_8fold
               WHEN '2013-2014' THEN m.urbanrural2013_2014_8fold
               WHEN '2016'   THEN m.urbanrural2016_8fold
               WHEN '2020'   THEN m.urbanrural2020_8fold
               WHEN '2022'   THEN m.urbanrural2022_8fold
           END AS rurality_8fold_stored,
           CASE m.rurality_version
               WHEN '2003-2004' THEN m.urbanrural2003_2004_status
               WHEN '2005-2006' THEN m.urbanrural2005_2006_status
               WHEN '2007-2008' THEN m.urbanrural2007_2008_status
               WHEN '2009-2010' THEN m.urbanrural2009_2010_status
               WHEN '2011-2012' THEN m.urbanrural2011_2012_status
               WHEN '2013-2014' THEN m.urbanrural2013_2014_status
               WHEN '2016'   THEN m.urbanrural2016_status
               WHEN '2020'   THEN m.urbanrural2020_status
               WHEN '2022'   THEN m.urbanrural2022_status
           END AS rurality_stored_status,
           '1 = most deprived' AS band_direction
    FROM matched m
),
reported AS (
    -- STEP 8a. POSTCODE STATUS. What happened to the postcode, independent of the year.
    SELECT s.*,
           CASE
               WHEN s.postcode_key IS NULL THEN 'missing_postcode'
               WHEN s.first_introduced_on IS NULL THEN 'not_found'
               WHEN s.matched_pc_norm IS NULL AND s.address_date IS NULL THEN 'missing_address_date'
               WHEN s.matched_pc_norm IS NULL AND s.address_date < s.first_introduced_on THEN 'postcode_not_yet_introduced'
               WHEN s.matched_pc_norm IS NULL AND s.next_life_introduced_on IS NOT NULL THEN 'between_lives'
               WHEN s.matched_pc_norm IS NULL THEN 'postcode_deleted_by_date'
               WHEN s.matched_candidate_count > 1 THEN 'ambiguous_postcode'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) NOT IN ('', 'A') THEN 'split_a_missing'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) = 'NOLINKP' THEN 'po_box'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) IN ('', 'NOLINK') THEN 'unlinked_large_user'
               WHEN s.source_pc_norm IS NULL THEN 'linked_small_user_not_found'
               WHEN s.matched_user_type = 'large_user' THEN 'linked_small_user'
               WHEN SUBSTRING(s.matched_pc_norm, LEN(s.matched_pc_base) + 1, 10) = 'A' THEN 'a_part'
               ELSE 'matched'
           END AS postcode_status
    FROM selected s
)
SELECT
    -- STEP 8b. REPORT. One row per input row. simd_status says whether the SIMD columns can be
    -- used: a year problem first, then a postcode problem, then a missing stored value.
    -- Product provenance and both keys are returned so the route can be reviewed
    -- (PHS checklist, p.25: state index, edition, weighting, direction and level).
       s.id, s.postcode, s.address_date, s.analysis_year, s.postcode_key,
       s.postcode_status,
       CASE
           WHEN s.edition_status <> 'ok' THEN s.edition_status
           WHEN s.postcode_status NOT IN ('matched', 'a_part', 'linked_small_user') THEN s.postcode_status
           WHEN s.simd_rank IS NULL OR s.phs_pw_scotland_quintile IS NULL OR s.phs_pw_scotland_decile IS NULL OR s.phs_pw_hb_quintile IS NULL OR s.phs_pw_hb_decile IS NULL OR s.phs_pw_hscp_quintile IS NULL OR s.phs_pw_hscp_decile IS NULL OR s.phs_pw_ca_quintile IS NULL OR s.phs_pw_ca_decile IS NULL OR s.phs_pw_most15pc IS NULL OR s.phs_pw_least15pc IS NULL OR s.gov_uw_scotland_quintile IS NULL OR s.gov_uw_scotland_decile IS NULL OR s.gov_uw_scotland_vigintile IS NULL OR s.data_zone_code IS NULL OR s.phs_hb_code IS NULL OR s.phs_hscp_code IS NULL OR s.phs_ca_code IS NULL THEN 'missing_simd'
           ELSE 'matched'
       END AS simd_status,
       'spd' AS index_source, s.index_release, 'postcode_grid_reference' AS allocation,
       s.simd_edition, s.edition_policy, s.data_zone_vintage,
       s.matched_pc_norm, s.matched_introduced_on, s.matched_is_current, s.matched_user_type,
       s.requested_link_postcode,
       s.source_pc_norm AS simd_source_pc_norm, s.source_introduced_on AS simd_source_introduced_on,
       s.source_is_current AS simd_source_is_current,
       s.data_zone_code, s.intermediate_zone_code, s.phs_hb_code, s.phs_hscp_code, s.phs_ca_code,
       s.simd_rank,
       s.phs_pw_scotland_quintile,
       s.phs_pw_scotland_decile,
       s.phs_pw_hb_quintile,
       s.phs_pw_hb_decile,
       s.phs_pw_hscp_quintile,
       s.phs_pw_hscp_decile,
       s.phs_pw_ca_quintile,
       s.phs_pw_ca_decile,
       s.phs_pw_most15pc,
       s.phs_pw_least15pc,
       s.gov_uw_scotland_quintile,
       s.gov_uw_scotland_decile,
       s.gov_uw_scotland_vigintile,
       s.band_direction,
       -- Rurality: the matched record's own Urban Rural Classification, in the version step 3b
       -- chose. rurality_status says whether the two codes can be used and, when they are
       -- empty, why: a postcode problem first, then no version for the year, then the reason
       -- stored with the record (outside_polygons, ambiguous_polygons, po_box). The codes come
       -- from this record's own grid reference, so read them beside matched_user_type; an
       -- ambiguous postcode or a B or C part has no single record and so no codes.
       s.rurality_version, s.rurality_policy,
       CASE WHEN s.postcode_status IN ('ambiguous_postcode', 'split_a_missing') THEN NULL ELSE s.rurality_6fold_stored END AS rurality_6fold,
       CASE WHEN s.postcode_status IN ('ambiguous_postcode', 'split_a_missing') THEN NULL ELSE s.rurality_8fold_stored END AS rurality_8fold,
       CASE
           WHEN s.matched_pc_norm IS NULL THEN s.postcode_status
           WHEN s.postcode_status IN ('ambiguous_postcode', 'split_a_missing') THEN s.postcode_status
           WHEN s.rurality_version IS NULL AND s.analysis_year IS NULL THEN 'missing_year'
           WHEN s.rurality_version IS NULL AND (s.analysis_year < 1 OR s.analysis_year > 9999) THEN 'invalid_year'
           WHEN s.rurality_version IS NULL AND s.analysis_year < 2003 THEN 'before_first_version'
           WHEN s.rurality_version IS NULL THEN 'invalid_year'
           WHEN s.rurality_stored_status IS NOT NULL THEN s.rurality_stored_status
           ELSE 'matched'
       END AS rurality_status,
       -- Own-record context: the matched record's NRS fields as ingested, names unchanged
       -- (Postcode as matched_postcode). For a large user these are its own fields, not the
       -- linked small user's; compare DataZone2011Code here with simd_source_pc_norm above.
       -- link_as_of.sql first gives the nearest lives when no life contains the address date.
       s.first_introduced_on, s.previous_life_deleted_on, s.next_life_introduced_on,
       s.matched_pc_base,
       s.matched_postcode,
       s.PostcodeDistrict,
       s.PostcodeSector,
       s.DateOfIntroduction,
       s.DateOfDeletion,
       s.SplitIndicator,
       s.CouncilArea2019Code,
       s.UKParliamentaryConstituency2024Code,
       s.ScottishParliamentaryRegion2026Code,
       s.ScottishParliamentaryConstituency2026Code,
       s.ElectoralWard2022Code,
       s.HealthBoardArea2019Code,
       s.HealthBoardArea2006Code,
       s.HealthBoardArea1995Code,
       s.IntegrationAuthority2019Code,
       s.OutputArea2022Code,
       s.OutputArea2011Code,
       s.OutputArea2001Code,
       s.OutputArea1991Code,
       s.DataZone2022Code,
       s.DataZone2011Code,
       s.DataZone2001Code,
       s.IntermediateZone2022Code,
       s.IntermediateZone2011Code,
       s.IntermediateZone2001Code,
       s.CensusHouseholdCount2022,
       s.CensusPopulationCount2022,
       s.CensusHouseholdCount2011,
       s.CensusPopulationCount2011,
       s.CensusHouseholdCount2001,
       s.CensusPopulationCount2001,
       s.CensusHouseholdCount1991,
       s.CensusPopulationCount1991,
       s.ScottishIndexOfMultipleDeprivation2020Rank,
       s.LAU2025Level1Code,
       s.ITL2025Level2Code,
       s.ITL2025Level3Code,
       s.Locality2020Code,
       s.Locality2022Code,
       s.Locality2001Code,
       s.Locality1991Code,
       s.Settlement2020Code,
       s.Settlement2022Code,
       s.Settlement2001Code,
       s.CivilParish1930Code,
       s.EnterpriseRegion2008Code,
       s.IslandCode,
       s.LocalGovernmentDistrict1995Code,
       s.LocalGovernmentDistrict1991Code,
       s.NationalPark2010Code,
       s.RegistrationDistrict2007Code,
       s.ROACommunityPlanningPartnership2006Code,
       s.ROALocal2006Code,
       s.StrategicDevelopmentPlanningArea2013Code,
       s.TravelToWorkArea2011Code,
       s.UrbanRural6Fold2022Code,
       s.UrbanRural8Fold2022Code,
       s.GridLinkIndicator,
       s.GridLinkPositionalAccuracy,
       s.NeverDigitised,
       s.LinkedSmallUserPostcode
FROM reported s;
