-- SPD SET, Scottish Postcode Directory (SPD): edition chosen by the YEAR OF THE HEALTH DATA (PHS v3.5 Table 4, section 3.2.1.1).
-- Reads postcode_simd_history, imported from results/postcode_simd_history.parquet with its natural key (pc_norm, introduced_on).
-- Standalone: no view, no other script, no other postcode product. Nothing is recalculated.
-- NRS did upstream: nothing: every life of every postcode is a row, and split postcodes are A/B/C rows.
-- Steps are numbered; each names the guidance it follows or says it is a project choice.
-- Guidance: PHS deprivation guidance v3.5 (Table 4 p.17, sections 3.1 to 3.4, Appendix A
-- pp.28-30), the PHS postcode-file page, the NRS SSPL information note and NRS dictionaries.
-- Executed on DuckDB and on SQL Server 2022; see ../LINKAGE_BY_ERA.md for the import recipe.
-- Columns named in export_contract.yaml are not returned; the Parquet keeps them.
-- Generated by python -m simd_ingest.sql_examples from the schemas; edit the generator.

WITH inputs AS (
    -- STEP 1. INPUT. Replace this SELECT with: SELECT id, postcode, analysis_year FROM your_cohort
    -- analysis_year is the year of the health data as an integer, not a SIMD label.
    -- id need not be unique; every input row comes back as one output row.
    SELECT 1 AS id, CAST('AB24 2TY' AS varchar(32)) AS postcode, 2020 AS analysis_year
),
requested AS (
    -- STEP 2. KEY. Uppercase and remove ASCII spaces, keeping the original text: the same rule
    -- as ingestion (project choice). Nothing is repaired and an NRS A/B/C suffix is not
    -- removed, so supply the ordinary postcode as a person writes it.
    SELECT id, postcode, CAST(NULL AS date) AS address_date, analysis_year,
           NULLIF(UPPER(REPLACE(postcode, ' ', '')), '') AS postcode_key
    FROM inputs
),
era AS (
    -- STEP 3. EDITION. PHS v3.5 Table 4, printed p.17: the year of the health data chooses the
    -- SIMD edition, and the edition fixes the data-zone vintage. Before 1996 there is no SIMD;
    -- the guidance points to Carstairs, which this table does not carry.
    SELECT * FROM (VALUES
        (1996, 2003, '2004', 2001),
        (2004, 2006, '2006', 2001),
        (2007, 2009, '2009v2', 2001),
        (2010, 2013, '2012', 2001),
        (2014, 2016, '2016', 2011),
        (2017, 9999, '2020v2', 2011)
    ) AS v(year_from, year_to, edition, data_zone_vintage)
),
chosen AS (
    SELECT r.id, r.postcode, r.address_date, r.analysis_year, r.postcode_key,
           e.edition AS simd_edition, e.data_zone_vintage,
           'PHS v3.5 Table 4: edition by year of the health data' AS edition_policy,
           CASE
               WHEN r.analysis_year IS NULL THEN 'missing_year'
               WHEN r.analysis_year < 1 OR r.analysis_year > 9999 THEN 'invalid_year'
               WHEN e.edition IS NULL THEN 'no_edition'
               ELSE 'ok'
           END AS edition_status
    FROM requested r
    LEFT JOIN era e ON r.analysis_year BETWEEN e.year_from AND e.year_to
),
-- BEGIN shared: from here to END shared the text is identical in link_by_era.sql and link_latest.sql of this set.
latest_lives AS (
    -- STEP 4. LATEST LIFE (SPD only). The directory keeps every life of a postcode. PHS's
    -- postcode file is "based on the most recent version of a postcode" and NRS's SSPL keeps
    -- "only the latest version", so take the newest introduction of each full NRS key,
    -- across both user types. A postcode that changed user type keeps its newest life only.
    -- This is not matching on an address date; use link_as_of.sql for that question.
    SELECT p.*,
           ROW_NUMBER() OVER (PARTITION BY p.pc_norm ORDER BY p.introduced_on DESC) AS life_number
    FROM postcode_simd_history p
),
latest AS (
    SELECT * FROM latest_lives WHERE life_number = 1
),
ranked AS (
    -- STEP 5. SPLIT PARTS (SPD only). An ordinary postcode can be several A/B/C rows. PHS
    -- "lookups include only the A part"; NRS uses A because it "contains more addresses".
    -- Project choice for the order: a live record first, then the whole record or the A
    -- part, then the newest introduction. A postcode whose best record is a B or C part gets
    -- no SIMD (split_a_missing); two equally good records get none either (ambiguous_postcode).
    SELECT l.*,
           DENSE_RANK() OVER (
               PARTITION BY l.pc_base
               ORDER BY CASE WHEN l.is_current = 1 THEN 0 ELSE 1 END,
                        CASE WHEN l.pc_norm = l.pc_base OR RIGHT(l.pc_norm, 1) = 'A' THEN 0 ELSE 1 END,
                        l.introduced_on DESC
           ) AS priority
    FROM latest l
),
candidates AS (
    SELECT r.*,
           COUNT(*) OVER (PARTITION BY r.pc_base) AS candidate_count,
           ROW_NUMBER() OVER (PARTITION BY r.pc_base ORDER BY r.pc_norm) AS candidate_number
    FROM ranked r
    WHERE r.priority = 1
),
representative AS (
    SELECT * FROM candidates WHERE candidate_number = 1
),
geography_source AS (
    -- STEP 6a. WHO CAN SUPPLY GEOGRAPHY. Small-user records of the latest lives, addressed by
    -- their exact key. The directory keeps a linked key's A/B/C suffix, so a large user linked
    -- to "AB1 2CDB" resolves to that B part exactly, as NRS recorded it.
    SELECT pc_norm AS source_key,
           pc_norm AS source_pc_norm,
           introduced_on AS source_introduced_on,
           is_current AS source_is_current,
           DataZone2001Code AS source_dz2001,
           DataZone2011Code AS source_dz2011,
           IntermediateZone2001Code AS source_iz2001,
           IntermediateZone2011Code AS source_iz2011,
           phs_dz2001_hb,
           phs_dz2001_hscp,
           phs_dz2001_ca,
           phs_dz2011_hb,
           phs_dz2011_hscp,
           phs_dz2011_ca,
           simd2004_rank,
           simd2004_pw_scotland_quintile,
           simd2004_pw_scotland_decile,
           simd2004_pw_hb_quintile,
           simd2004_pw_hb_decile,
           simd2004_pw_hscp_quintile,
           simd2004_pw_hscp_decile,
           simd2004_pw_ca_quintile,
           simd2004_pw_ca_decile,
           simd2004_most15pc,
           simd2004_least15pc,
           simd2004_uw_scotland_quintile,
           simd2004_uw_scotland_decile,
           simd2004_uw_scotland_vigintile,
           simd2006_rank,
           simd2006_pw_scotland_quintile,
           simd2006_pw_scotland_decile,
           simd2006_pw_hb_quintile,
           simd2006_pw_hb_decile,
           simd2006_pw_hscp_quintile,
           simd2006_pw_hscp_decile,
           simd2006_pw_ca_quintile,
           simd2006_pw_ca_decile,
           simd2006_most15pc,
           simd2006_least15pc,
           simd2006_uw_scotland_quintile,
           simd2006_uw_scotland_decile,
           simd2006_uw_scotland_vigintile,
           simd2009v2_rank,
           simd2009v2_pw_scotland_quintile,
           simd2009v2_pw_scotland_decile,
           simd2009v2_pw_hb_quintile,
           simd2009v2_pw_hb_decile,
           simd2009v2_pw_hscp_quintile,
           simd2009v2_pw_hscp_decile,
           simd2009v2_pw_ca_quintile,
           simd2009v2_pw_ca_decile,
           simd2009v2_most15pc,
           simd2009v2_least15pc,
           simd2009v2_uw_scotland_quintile,
           simd2009v2_uw_scotland_decile,
           simd2009v2_uw_scotland_vigintile,
           simd2012_rank,
           simd2012_pw_scotland_quintile,
           simd2012_pw_scotland_decile,
           simd2012_pw_hb_quintile,
           simd2012_pw_hb_decile,
           simd2012_pw_hscp_quintile,
           simd2012_pw_hscp_decile,
           simd2012_pw_ca_quintile,
           simd2012_pw_ca_decile,
           simd2012_most15pc,
           simd2012_least15pc,
           simd2012_uw_scotland_quintile,
           simd2012_uw_scotland_decile,
           simd2012_uw_scotland_vigintile,
           simd2016_rank,
           simd2016_pw_scotland_quintile,
           simd2016_pw_scotland_decile,
           simd2016_pw_hb_quintile,
           simd2016_pw_hb_decile,
           simd2016_pw_hscp_quintile,
           simd2016_pw_hscp_decile,
           simd2016_pw_ca_quintile,
           simd2016_pw_ca_decile,
           simd2016_most15pc,
           simd2016_least15pc,
           simd2016_uw_scotland_quintile,
           simd2016_uw_scotland_decile,
           simd2016_uw_scotland_vigintile,
           simd2020v2_rank,
           simd2020v2_pw_scotland_quintile,
           simd2020v2_pw_scotland_decile,
           simd2020v2_pw_hb_quintile,
           simd2020v2_pw_hb_decile,
           simd2020v2_pw_hscp_quintile,
           simd2020v2_pw_hscp_decile,
           simd2020v2_pw_ca_quintile,
           simd2020v2_pw_ca_decile,
           simd2020v2_most15pc,
           simd2020v2_least15pc,
           simd2020v2_uw_scotland_quintile,
           simd2020v2_uw_scotland_decile,
           simd2020v2_uw_scotland_vigintile
    FROM latest
    WHERE spd_user_type = 'small_user'
),
matched AS (
    -- STEP 6b. LARGE USERS. PHS v3.5 Appendix A, p.30: a large-user postcode has no boundary;
    -- where NRS could link it to a small-user postcode, that postcode supplies the geography;
    -- a PO box (NO LINKP) or an unlinked large user (NO LINK) gets none. A small user supplies
    -- its own geography. Never the large user's own zone, never another product, never a chain
    -- through a second large user. The large user's own fields stay visible as context below.
    SELECT c.*,
           r.pc_norm AS matched_pc_norm, r.introduced_on AS matched_introduced_on,
           r.is_current AS matched_is_current, r.spd_user_type AS matched_user_type,
           r.LinkedSmallUserPostcode AS requested_link_postcode,
           r.candidate_count AS matched_candidate_count, r.spd_release AS index_release,
           r.pc_base AS matched_pc_base,
           r.Postcode AS matched_postcode,
           r.PostcodeDistrict,
           r.PostcodeSector,
           r.DateOfIntroduction,
           r.DateOfDeletion,
           r.SplitIndicator,
           r.CouncilArea2019Code,
           r.UKParliamentaryConstituency2024Code,
           r.ScottishParliamentaryRegion2026Code,
           r.ScottishParliamentaryConstituency2026Code,
           r.ElectoralWard2022Code,
           r.HealthBoardArea2019Code,
           r.HealthBoardArea2006Code,
           r.HealthBoardArea1995Code,
           r.IntegrationAuthority2019Code,
           r.OutputArea2022Code,
           r.OutputArea2011Code,
           r.OutputArea2001Code,
           r.OutputArea1991Code,
           r.DataZone2022Code,
           r.DataZone2011Code,
           r.DataZone2001Code,
           r.IntermediateZone2022Code,
           r.IntermediateZone2011Code,
           r.IntermediateZone2001Code,
           r.CensusHouseholdCount2022,
           r.CensusPopulationCount2022,
           r.CensusHouseholdCount2011,
           r.CensusPopulationCount2011,
           r.CensusHouseholdCount2001,
           r.CensusPopulationCount2001,
           r.CensusHouseholdCount1991,
           r.CensusPopulationCount1991,
           r.ScottishIndexOfMultipleDeprivation2020Rank,
           r.LAU2025Level1Code,
           r.ITL2025Level2Code,
           r.ITL2025Level3Code,
           r.Locality2020Code,
           r.Locality2022Code,
           r.Locality2001Code,
           r.Locality1991Code,
           r.Settlement2020Code,
           r.Settlement2022Code,
           r.Settlement2001Code,
           r.CivilParish1930Code,
           r.EnterpriseRegion2008Code,
           r.IslandCode,
           r.LocalGovernmentDistrict1995Code,
           r.LocalGovernmentDistrict1991Code,
           r.NationalPark2010Code,
           r.RegistrationDistrict2007Code,
           r.ROACommunityPlanningPartnership2006Code,
           r.ROALocal2006Code,
           r.StrategicDevelopmentPlanningArea2013Code,
           r.TravelToWorkArea2011Code,
           r.UrbanRural6Fold2022Code,
           r.UrbanRural8Fold2022Code,
           r.GridLinkIndicator,
           r.GridLinkPositionalAccuracy,
           r.NeverDigitised,
           r.LinkedSmallUserPostcode,
           g.*
    FROM chosen c
    LEFT JOIN representative r ON r.pc_base = c.postcode_key
    LEFT JOIN geography_source g ON g.source_key = CASE
        WHEN r.candidate_count > 1 THEN NULL
        WHEN r.pc_norm <> r.pc_base AND RIGHT(r.pc_norm, 1) <> 'A' THEN NULL
        WHEN r.spd_user_type = 'small_user' THEN r.pc_norm
        ELSE UPPER(REPLACE(r.LinkedSmallUserPostcode, ' ', ''))
    END
),
selected AS (
    -- STEP 7. VALUES. Copy the stored values of the chosen edition from the record that
    -- supplies the geography, through the data zone of that edition's vintage (PHS Table 4:
    -- 2001 zones for 2004 to 2012, 2011 zones for 2016 and 2020v2). The intermediate zone of
    -- the same vintage, which nests those data zones, comes with it. The three PHS codes are the
    -- areas PHS used for the within-board, within-HSCP and within-council bands (section 3.4):
    -- use them, not the NRS administrative codes, with those bands. Every one of the 14
    -- stored measures is copied: PHS population-weighted bands and flags (pw), Scottish
    -- Government unweighted bands (uw); never mix the two in one analysis (sections 3.1.2,
    -- 3.3). Band 1 is most deprived in every edition; ingestion already reversed the 2004 and
    -- 2006 PHS bands, so nothing is reversed here.
    SELECT m.*,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.source_dz2001
               WHEN 2011     THEN m.source_dz2011
           END AS data_zone_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.source_iz2001
               WHEN 2011     THEN m.source_iz2011
           END AS intermediate_zone_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_hb
               WHEN 2011     THEN m.phs_dz2011_hb
           END AS phs_hb_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_hscp
               WHEN 2011     THEN m.phs_dz2011_hscp
           END AS phs_hscp_code,
           CASE m.data_zone_vintage
               WHEN 2001     THEN m.phs_dz2001_ca
               WHEN 2011     THEN m.phs_dz2011_ca
           END AS phs_ca_code,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_rank
               WHEN '2006'   THEN m.simd2006_rank
               WHEN '2009v2' THEN m.simd2009v2_rank
               WHEN '2012'   THEN m.simd2012_rank
               WHEN '2016'   THEN m.simd2016_rank
               WHEN '2020v2' THEN m.simd2020v2_rank
           END AS simd_rank,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_scotland_quintile
               WHEN '2006'   THEN m.simd2006_pw_scotland_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_scotland_quintile
               WHEN '2012'   THEN m.simd2012_pw_scotland_quintile
               WHEN '2016'   THEN m.simd2016_pw_scotland_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_scotland_quintile
           END AS phs_pw_scotland_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_scotland_decile
               WHEN '2006'   THEN m.simd2006_pw_scotland_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_scotland_decile
               WHEN '2012'   THEN m.simd2012_pw_scotland_decile
               WHEN '2016'   THEN m.simd2016_pw_scotland_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_scotland_decile
           END AS phs_pw_scotland_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hb_quintile
               WHEN '2006'   THEN m.simd2006_pw_hb_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_hb_quintile
               WHEN '2012'   THEN m.simd2012_pw_hb_quintile
               WHEN '2016'   THEN m.simd2016_pw_hb_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_hb_quintile
           END AS phs_pw_hb_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hb_decile
               WHEN '2006'   THEN m.simd2006_pw_hb_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_hb_decile
               WHEN '2012'   THEN m.simd2012_pw_hb_decile
               WHEN '2016'   THEN m.simd2016_pw_hb_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_hb_decile
           END AS phs_pw_hb_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hscp_quintile
               WHEN '2006'   THEN m.simd2006_pw_hscp_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_hscp_quintile
               WHEN '2012'   THEN m.simd2012_pw_hscp_quintile
               WHEN '2016'   THEN m.simd2016_pw_hscp_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_hscp_quintile
           END AS phs_pw_hscp_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_hscp_decile
               WHEN '2006'   THEN m.simd2006_pw_hscp_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_hscp_decile
               WHEN '2012'   THEN m.simd2012_pw_hscp_decile
               WHEN '2016'   THEN m.simd2016_pw_hscp_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_hscp_decile
           END AS phs_pw_hscp_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_ca_quintile
               WHEN '2006'   THEN m.simd2006_pw_ca_quintile
               WHEN '2009v2' THEN m.simd2009v2_pw_ca_quintile
               WHEN '2012'   THEN m.simd2012_pw_ca_quintile
               WHEN '2016'   THEN m.simd2016_pw_ca_quintile
               WHEN '2020v2' THEN m.simd2020v2_pw_ca_quintile
           END AS phs_pw_ca_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_pw_ca_decile
               WHEN '2006'   THEN m.simd2006_pw_ca_decile
               WHEN '2009v2' THEN m.simd2009v2_pw_ca_decile
               WHEN '2012'   THEN m.simd2012_pw_ca_decile
               WHEN '2016'   THEN m.simd2016_pw_ca_decile
               WHEN '2020v2' THEN m.simd2020v2_pw_ca_decile
           END AS phs_pw_ca_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_most15pc
               WHEN '2006'   THEN m.simd2006_most15pc
               WHEN '2009v2' THEN m.simd2009v2_most15pc
               WHEN '2012'   THEN m.simd2012_most15pc
               WHEN '2016'   THEN m.simd2016_most15pc
               WHEN '2020v2' THEN m.simd2020v2_most15pc
           END AS phs_pw_most15pc,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_least15pc
               WHEN '2006'   THEN m.simd2006_least15pc
               WHEN '2009v2' THEN m.simd2009v2_least15pc
               WHEN '2012'   THEN m.simd2012_least15pc
               WHEN '2016'   THEN m.simd2016_least15pc
               WHEN '2020v2' THEN m.simd2020v2_least15pc
           END AS phs_pw_least15pc,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_quintile
               WHEN '2006'   THEN m.simd2006_uw_scotland_quintile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_quintile
               WHEN '2012'   THEN m.simd2012_uw_scotland_quintile
               WHEN '2016'   THEN m.simd2016_uw_scotland_quintile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_quintile
           END AS gov_uw_scotland_quintile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_decile
               WHEN '2006'   THEN m.simd2006_uw_scotland_decile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_decile
               WHEN '2012'   THEN m.simd2012_uw_scotland_decile
               WHEN '2016'   THEN m.simd2016_uw_scotland_decile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_decile
           END AS gov_uw_scotland_decile,
           CASE m.simd_edition
               WHEN '2004'   THEN m.simd2004_uw_scotland_vigintile
               WHEN '2006'   THEN m.simd2006_uw_scotland_vigintile
               WHEN '2009v2' THEN m.simd2009v2_uw_scotland_vigintile
               WHEN '2012'   THEN m.simd2012_uw_scotland_vigintile
               WHEN '2016'   THEN m.simd2016_uw_scotland_vigintile
               WHEN '2020v2' THEN m.simd2020v2_uw_scotland_vigintile
           END AS gov_uw_scotland_vigintile,
           '1 = most deprived' AS band_direction
    FROM matched m
),
reported AS (
    -- STEP 8a. POSTCODE STATUS. What happened to the postcode, independent of the year.
    SELECT s.*,
           CASE
               WHEN s.postcode_key IS NULL THEN 'missing_postcode'
               WHEN s.matched_pc_norm IS NULL THEN 'not_found'
               WHEN s.matched_candidate_count > 1 THEN 'ambiguous_postcode'
               WHEN s.matched_pc_norm <> s.matched_pc_base AND RIGHT(s.matched_pc_norm, 1) <> 'A' THEN 'split_a_missing'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) = 'NOLINKP' THEN 'po_box'
               WHEN s.matched_user_type = 'large_user'
                    AND UPPER(REPLACE(COALESCE(s.requested_link_postcode, ''), ' ', '')) IN ('', 'NOLINK') THEN 'unlinked_large_user'
               WHEN s.source_pc_norm IS NULL THEN 'linked_small_user_not_found'
               WHEN s.matched_user_type = 'large_user' THEN 'linked_small_user'
               WHEN s.matched_pc_norm <> s.matched_pc_base THEN 'a_part'
               ELSE 'matched'
           END AS postcode_status
    FROM selected s
)
SELECT
    -- STEP 8b. REPORT. One row per input row. simd_status says whether the SIMD columns can be
    -- used: a year problem first, then a postcode problem, then a missing stored value.
    -- Product provenance and both keys are returned so the route can be reviewed
    -- (PHS checklist, p.25: state index, edition, weighting, direction and level).
       s.id, s.postcode, s.address_date, s.analysis_year, s.postcode_key,
       s.postcode_status,
       CASE
           WHEN s.edition_status <> 'ok' THEN s.edition_status
           WHEN s.postcode_status NOT IN ('matched', 'a_part', 'linked_small_user') THEN s.postcode_status
           WHEN s.simd_rank IS NULL OR s.phs_pw_scotland_quintile IS NULL OR s.phs_pw_scotland_decile IS NULL OR s.phs_pw_hb_quintile IS NULL OR s.phs_pw_hb_decile IS NULL OR s.phs_pw_hscp_quintile IS NULL OR s.phs_pw_hscp_decile IS NULL OR s.phs_pw_ca_quintile IS NULL OR s.phs_pw_ca_decile IS NULL OR s.phs_pw_most15pc IS NULL OR s.phs_pw_least15pc IS NULL OR s.gov_uw_scotland_quintile IS NULL OR s.gov_uw_scotland_decile IS NULL OR s.gov_uw_scotland_vigintile IS NULL OR s.data_zone_code IS NULL OR s.phs_hb_code IS NULL OR s.phs_hscp_code IS NULL OR s.phs_ca_code IS NULL THEN 'missing_simd'
           ELSE 'matched'
       END AS simd_status,
       'spd' AS index_source, s.index_release, 'postcode_grid_reference' AS allocation,
       s.simd_edition, s.edition_policy, s.data_zone_vintage,
       s.matched_pc_norm, s.matched_introduced_on, s.matched_is_current, s.matched_user_type,
       s.requested_link_postcode,
       s.source_pc_norm AS simd_source_pc_norm, s.source_introduced_on AS simd_source_introduced_on,
       s.source_is_current AS simd_source_is_current,
       s.data_zone_code, s.intermediate_zone_code, s.phs_hb_code, s.phs_hscp_code, s.phs_ca_code,
       s.simd_rank,
       s.phs_pw_scotland_quintile,
       s.phs_pw_scotland_decile,
       s.phs_pw_hb_quintile,
       s.phs_pw_hb_decile,
       s.phs_pw_hscp_quintile,
       s.phs_pw_hscp_decile,
       s.phs_pw_ca_quintile,
       s.phs_pw_ca_decile,
       s.phs_pw_most15pc,
       s.phs_pw_least15pc,
       s.gov_uw_scotland_quintile,
       s.gov_uw_scotland_decile,
       s.gov_uw_scotland_vigintile,
       s.band_direction,
       -- Own-record context: the matched record's NRS fields as ingested, names unchanged
       -- (Postcode as matched_postcode). For a large user these are its own fields, not the
       -- linked small user's; compare DataZone2011Code here with simd_source_pc_norm above.
       -- link_as_of.sql first gives the nearest lives when no life contains the address date.
       s.matched_pc_base,
       s.matched_postcode,
       s.PostcodeDistrict,
       s.PostcodeSector,
       s.DateOfIntroduction,
       s.DateOfDeletion,
       s.SplitIndicator,
       s.CouncilArea2019Code,
       s.UKParliamentaryConstituency2024Code,
       s.ScottishParliamentaryRegion2026Code,
       s.ScottishParliamentaryConstituency2026Code,
       s.ElectoralWard2022Code,
       s.HealthBoardArea2019Code,
       s.HealthBoardArea2006Code,
       s.HealthBoardArea1995Code,
       s.IntegrationAuthority2019Code,
       s.OutputArea2022Code,
       s.OutputArea2011Code,
       s.OutputArea2001Code,
       s.OutputArea1991Code,
       s.DataZone2022Code,
       s.DataZone2011Code,
       s.DataZone2001Code,
       s.IntermediateZone2022Code,
       s.IntermediateZone2011Code,
       s.IntermediateZone2001Code,
       s.CensusHouseholdCount2022,
       s.CensusPopulationCount2022,
       s.CensusHouseholdCount2011,
       s.CensusPopulationCount2011,
       s.CensusHouseholdCount2001,
       s.CensusPopulationCount2001,
       s.CensusHouseholdCount1991,
       s.CensusPopulationCount1991,
       s.ScottishIndexOfMultipleDeprivation2020Rank,
       s.LAU2025Level1Code,
       s.ITL2025Level2Code,
       s.ITL2025Level3Code,
       s.Locality2020Code,
       s.Locality2022Code,
       s.Locality2001Code,
       s.Locality1991Code,
       s.Settlement2020Code,
       s.Settlement2022Code,
       s.Settlement2001Code,
       s.CivilParish1930Code,
       s.EnterpriseRegion2008Code,
       s.IslandCode,
       s.LocalGovernmentDistrict1995Code,
       s.LocalGovernmentDistrict1991Code,
       s.NationalPark2010Code,
       s.RegistrationDistrict2007Code,
       s.ROACommunityPlanningPartnership2006Code,
       s.ROALocal2006Code,
       s.StrategicDevelopmentPlanningArea2013Code,
       s.TravelToWorkArea2011Code,
       s.UrbanRural6Fold2022Code,
       s.UrbanRural8Fold2022Code,
       s.GridLinkIndicator,
       s.GridLinkPositionalAccuracy,
       s.NeverDigitised,
       s.LinkedSmallUserPostcode
FROM reported s;
-- END shared
